blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.list_posts.as_view(), name='index'),
    path('<int:pk>/', views.detail_post.as_view(), name='detail'),
    path('create/', views.create_post.as_view(), name='create'),
    path('update/<int:pk>/', views.update_post.as_view(), name='update'),
    path('delete/<int:pk>/', views.delete_post.as_view(), name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('categories/', views.category_list.as_view(), name='categories'),
    path('categories/<int:pk>', views.category_detail.as_view(), name='category'),
]

lab2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Post(models.Model):
    título = models.CharField(max_length=255)
    conteúdo = models.TextField()
    data_de_postagem = models.DateTimeField()

class Comment(models.Model):
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    data_da_postagem = models.DateTimeField()
    texto = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['-data_da_postagem']

class Category(models.Model):
    nome = models.CharField(max_length=100)
    descrição = models.TextField()
    post = models.ManyToManyField(Post)

blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .models import Post, Comment, Category
from .form import PostForm, CommentForm

# Create your views here.

class list_posts(ListView):
    model = Post
    template_name = 'blog/index.html'

class detail_post(DetailView):
    model = Post
    template_name = 'blog/detail.html'

class create_post(CreateView):
    model = Post
    template_name = 'blog/create.html'
    fields = ['título','data_de_postagem','conteúdo']
    success_url = reverse_lazy('blog:index')
    
class update_post(UpdateView):
    model = Post
    template_name = 'blog/update.html'
    fields = ['título','data_de_postagem','conteúdo']
    success_url = reverse_lazy('blog:index')



class delete_post(DeleteView):
    model = Post
    template_name = 'blog/delete.html'
    success_url = reverse_lazy('blog:index')


def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_autor = form.cleaned_data['autor']
            comment_texto = form.cleaned_data['texto']
            comment_data_da_postagem = form.cleaned_data['data_da_postagem']
            comment = Comment(autor=comment_autor,
                            texto=comment_texto,
                            data_da_postagem=comment_data_da_postagem,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('blog:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'blog/comment.html', context)

class category_detail(DetailView):
    model = Category
    template_name = 'blog/category.html'

class category_list(ListView):
    model = Category
    template_name = 'blog/categories.html'

blog/templates/blog/categories.html
{% extends 'base.html' %} {% block content %}
<h2>Todas as Categorias</h2>
{% if category_list %}
<section class="lista-de-cards">
    {% for category in category_list %}
    <article class="card">
      <a href="{% url 'blog:category' category.id %}">{{ category.nome }}</a>
    </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma categoria.</p>
{% endif %} {% endblock content %}

blog/templates/blog/category.html
{% extends 'base.html' %} {% block content %}
<h2>{{category.nome}}</h2>
{% if category.post.all %}
<section class="lista-de-cards">
    {% for post in category.post.all %}
    <article class="card">
      <a href="{% url 'blog:detail' post.id %}">details</a>
      <p>{{ post.título }} ({{ post.data_de_postagem }})</p>
    </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post.</p>
{% endif %} {% endblock content %}

blog/templates/blog/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar post {{ post.título }} ({{ post.data_de_postagem }})</h2>

<form action="{% url 'blog:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'blog:detail' post.id %}">Voltar para a página do post</a></p>
{% endblock content %}

blog/templates/blog/create.html
{% extends 'base.html' %} {% block content %}
<h2>Inserir Novo Post</h2>
<form method="POST" action="{% url 'blog:create' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Criar</button>
</form>

{% endblock content %}

blog/templates/blog/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'blog:delete' post.id %}" method="post">
  {% csrf_token %}
  <p>
    Você tem certeza que deseja apagar o post "{{ post.título }} ({{ post.data_de_postagem }})"?
  </p>
  <button type="submit">Apagar</button>
</form>
{% endblock content %}

blog/templates/blog/detail.html
{% extends 'base.html' %} {% block title %} {{ post.título }} ({{
    post.data_de_postagem | date }}) {% endblock title %} {% block content %}
    <h2>Detalhes do Filme {{ post.título }} ({{ post.data_de_postagem | date }})</h2>
    
    <section class="dados-de-post">
      <p> {{ post.conteúdo | safe }} </p> 
      <ul>
        <li>Título: {{ post.título }}</li>
        <li>Data de Postagem: {{ post.data_de_postagem }}</li>
        <li><a href="{% url 'blog:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'blog:delete' post.id %}">Apagar</a></li>
      </ul>
    </section>

    <hr>

    <section>
        <header>
            <h3>Comentários</h3>
        </header>
        <ul>
            {% if post.comment_set.all %}
                {% for comment in post.comment_set.all %}
                    <figure>
                        <blockquote>
                            "{{ comment.texto }}"
                        </blockquote>
                        <figcaption>—{{ comment.autor }}</figcaption>
                    </figure>
                {% endfor %}
            {% else %}
                <p>Ainda não existe nenhuma comentário para este post.</p>
            {% endif %}
        </ul>

        <a href="{% url 'blog:comment' post.id %}"><button>Crie seu Comentário</button></a>
    </section>

    <section>
        <header>
            <h3>Categorias</h3>
        </header>
        <ul>
            {% if post.category_set.all %}
                {% for category in post.category_set.all %}
                    <a href="{% url 'blog:category' category.id %}">{{ category.nome }}</a>
                {% endfor %}
            {% else %}
                <p>Ainda não existe nenhuma categoria para este post.</p>
            {% endif %}
        </ul>
    </section>
    
    {% endblock content %}

blog/templates/blog/index.html
{% extends 'base.html' %} {% block content %}
<h2>Todos os Filmes</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
      <a href="{% url 'blog:detail' post.id %}">details</a>
      <p>{{ post.título }} ({{ post.data_de_postagem }})</p>
    </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post.</p>
{% endif %} {% endblock content %}

blog/templates/blog/update.html
{% extends 'base.html' %}
{% block content %}
<h2>Atualizar Dados do Post {{ post.título }} ({{ post.data_de_postagem }})</h2>
<form method="post" action="{% url 'blog:update' post.id%}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Atualizar</button>
</form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Blog!
    </title>
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'blog:index' %}">
            <p>Blog</p>
        </a>
        <nav id="navegacao-principal">
            <ul>
              <li><a href="{% url 'blog:index' %}">Post</a></li>
              <li><a href="{% url 'blog:create' %}">Create</a></li>
              <li><a href="{% url 'blog:categories' %}">Categories</a></li>
            </ul>
          </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>